# Generated by Django 4.1.7 on 2023-04-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_product_cat_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
